"""empty message

Revision ID: 390449e84d2e
Revises: 3d5ad6ecac91
Create Date: 2023-10-28 19:07:53.534494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '390449e84d2e'
down_revision = '3d5ad6ecac91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
